version: "3.7"
services:
    captcha-for-all:
        build:
            dockerfile: docker/Dockerfile
            context: .

        restart: always

        ports:
            - 80

    postgres:
        image: postgres:14.11-alpine

        volumes:
            - ./databaseEntrypoint:/docker-entrypoint-initdb.d
            - captchaForAllPostgresqlData:/var/lib/postgresql/data

volumes:
    captchaForAllPostgresqlData:
        driver: local
